### ISSUE TITLE
Error in masterCreate

### ISSUE THREAD

**Issue by janneboman** [wallabyway/bim360-project-starter#2]
click this link to open new Project: https://docs.b360.autodesk.com/projects/3808cc00-ee90-43da-a6e0-333fc6b47109/folders/urn:adsk.wipprod:fs.folder:co.T6FF_OX2TJG3y2mC4wWOWA/detail
In the meantime, I"m copying the Files over... back soon
copying folder: urn:adsk.wipprod:fs.folder:co.vwtqX3J_QGyfJo4SzohE9Q to urn:adsk.wipprod:fs.folder:co.T6FF_OX2TJG3y2mC4wWOWA
file:///usr/lib/node_modules/bim360-project-starter/fileutils.mjs:32
		for (const file of sdir) {
		                   ^

**TypeError: sdir is not iterable
    at fileutils.copyFolderRecursively (file:///usr/lib/node_modules/bim360-project-starter/fileutils.mjs:32:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///usr/lib/node_modules/bim360-project-starter/cli.mjs:77:2)**

Node.js v19.8.1

**Comment by janneboman** [comment]
It did however proceed to copy template, so I'm unsure how critical this error is...?

![image](https://user-images.githubusercontent.com/11683126/230549022-5e290d94-3efc-45d7-a442-0e4e34b62068.png)

**Comment by wallabyway** [comment]
Ok, I updated the code, and added a walkthrough video.

Please try again now.
